
name: windows-multi

on:
  workflow_dispatch:      # 仅手动触发

jobs:
  windows-multi:
    strategy:
      fail-fast: false
      matrix:
        ver:
          - { cv: 4.8.1 }
        list:
          - { win_ver: 2019, vs_name: vs2015, vs_ver: v140 }   # VS2015 使用 windows-2019 镜像
         # - { win_ver: 2022, vs_name: vs2022, vs_ver: v143 }   # VS2022 使用 windows-2022 镜像
        crt: [md, mt]
        build_type: [Debug, Release]

    runs-on: windows-${{ matrix.list.win_ver }}
    name: windows-${{ matrix.list.vs_name }}-${{ matrix.crt }}-${{ matrix.build_type }}

    env:
      PKG_NAME: opencv-${{ matrix.ver.cv }}-windows-${{ matrix.list.vs_name }}-${{ matrix.crt }}-${{ matrix.build_type }}

    steps:
      - uses: actions/checkout@v4

      - name: checkout opencv
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv
          path: opencv-${{ matrix.ver.cv }}
          ref: ${{ matrix.ver.cv }}
          submodules: recursive

      - name: copy
        run: |
          cp build-opencv4-multi.bat opencv-${{ matrix.ver.cv }}
          cp opencv4_cmake_options.txt opencv-${{ matrix.ver.cv }}

      - name: build
        run: |
          cd opencv-${{ matrix.ver.cv }}
          ./build-opencv4-multi.bat ${{ matrix.list.vs_ver }} ${{ matrix.crt }} ${{ matrix.build_type }}

      - name: 7zip
        run: |
          cp -r opencv-${{ matrix.ver.cv }}/build-x64-${{ matrix.list.vs_ver }}-${{ matrix.crt }}-${{ matrix.build_type }}/install windows-x64
          cp -r opencv-${{ matrix.ver.cv }}/build-Win32-${{ matrix.list.vs_ver }}-${{ matrix.crt }}-${{ matrix.build_type }}/install windows-x86
          7z a ${{ env.PKG_NAME }}.7z windows-x64 windows-x86
          rm windows-x64 -r -fo
          rm windows-x86 -r -fo

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_NAME }}.7z
